### PR TITLE
Fix `os.pathsep` support in Jinja

### LINKED ISSUE #5704: Using `os.pathsep` worked in conda-build 25.3 & fails in 25.4
Given the following recipe

```yaml
# filename: use_os_pathsep_jinja/meta.yaml

package:
  name: use_os_pathsep_jinja
  version: 1

build:
  number: 0
  noarch: generic
  script:
    - echo "{{ os.pathsep }}"
```

With conda-build 25.3 this will print on UNIX `:` or Windows `;`

However conda-build 25.4 errors with

```python
CondaBuildUserError: Failed to render jinja template in /home/conda/use_os_pathsep_jinja/meta.yaml:
'type object' has no attribute 'pathsep'
```

### PR DESCRIPTION
**Pull request by jakirkham**
Previously `os.pathsep` was supported in conda-build 25.3. However it appears locking down Jinja usage of `os` introduced a regression in 25.4 that dropped `os.pathsep` support. To fix this ensure `os.pathsep` is exposed to Jinja and test for it.

Fixes https://github.com/conda/conda-build/issues/5704

### CODE REVIEW

**Review by jaimergp — DISMISSED** [review]

File: conda_build/metadata.py [hunk 1]
```diff
@@ -321,6 +321,7 @@ def evalidate_model():
         # for legacy os attributes
         "environ",
         "getenv",
+        "pathsep",
```
Comment (jakirkham) [inline conda_build/metadata.py:324]: This should fix the CI failures popping up in a few jobs

**Review by kenodegard — CHANGES_REQUESTED** [review]
I think this needs a news file

**Comment by jakirkham** [comment]
Added a news entry

The other CI issue is unrelated

It is caused by a test that did not pin the source artifact it used. So a new version of that artifact broke the test. More details in issue ( https://github.com/conda/conda-build/issues/5706 ) and associated PR

**Review by jezdez — APPROVED** [review]

**Review by kenodegard — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 🙏
