### ISSUE TITLE
Build fails with gcc 7.3.0 when building two dependent projects

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#3131]
### Actual Behavior

I have a project, that builds a shared lib and an executable that uses the lib on linux-64 using the defaults channel only. The lib privately depends on zmq but does not publish this dependency. The exe uses the lib by calling a function in it. Both are built and installed in the same conda package.

Using gcc 7.3.0 the compilation of lib and exe succeeds but linking the exe throws an error that the dependency "libzmq" is not found:

```
/home/gabm/miniconda3/conda-bld/condatest_1536660221860/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libzmq.so.5, needed by libcondatestlib.so, not found (try using -rpath or -rpath-link)
/home/gabm/miniconda3/conda-bld/condatest_1536660221860/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: libcondatestlib.so: undefined reference to `zmq_ctx_shutdown'
/home/gabm/miniconda3/conda-bld/condatest_1536660221860/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: libcondatestlib.so: undefined reference to `zmq_ctx_new'
```

Doing the same while specifying gcc to be 7.2.0 works.

```yaml
cxx_compiler_version:
  - 7.2.0 

c_compiler_version:
  - 7.2.0 
```

### Expected Behavior

It should work with 7.3.0 as well.

### Steps to Reproduce

- clone https://github.com/gabm/condatest
- conda-build recipe

##### `Output of conda info`

```

```

**Comment by gabm** [comment]
The full build log with 7.3.0 is here: https://pastebin.com/4Shjqhf2

The full build log with 7.2.0 is here: https://pastebin.com/QuBM36CK

**Comment by msarahan** [comment]
@mingwandroid would have to answer how valid an indirect dependency is.  In my mind, if you call a function from a library, that's not an indirect dependency.  It's direct, and by not explicitly linking it, you are not following basic rules of how to build software and should not expect things to work.

Also, this is not a conda-build issue.  The compilers are packages, and any discussion of them outside of how they get chosen by conda-build belongs on https://github.com/continuumio/anaconda-issues
