### ISSUE TITLE
Unexpected `binary is None` in `liefldd.py`

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#4787]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

With the last conda-smithy release, conda-forge is now back to using lief 0.12.3, and failing in https://github.com/conda-forge/compiler-rt-feedstock/pull/61 with:
```
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/os_utils/liefldd.py", line 406, in inspect_linkages_lief
    if binary.format == lief.EXE_FORMATS.ELF:
AttributeError: 'NoneType' object has no attribute 'format'
```

### Conda Info

```shell
conda-forge CI for osx-64 / osx-arm64
```

### Conda Config

```shell
conda-forge CI for osx-64 / osx-arm64
```

### Conda list

host env:
```shell
environment location: /Users/runner/miniforge3/conda-bld/compiler-rt-packages_1677355103841/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol


The following NEW packages will be INSTALLED:

    clang:           16.0.0.rc3-h9d310f0_0         conda-forge/label/llvm_rc
    clang-16:        16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    clang-format:    16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    clang-format-16: 16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    clang-tools:     16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    clangdev:        16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    clangxx:         16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    icu:             70.1-h96cf925_0               conda-forge              
    libclang:        16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    libclang-cpp:    16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    libclang-cpp16:  16.0.0.rc3-default_h5b99a12_0 conda-forge/label/llvm_rc
    libclang13:      16.0.0.rc3-default_h4e9855e_0 conda-forge/label/llvm_rc
    libcxx:          14.0.6-hccf4f1f_0             conda-forge              
    libiconv:        1.17-hac89ed1_0               conda-forge              
    libllvm16:       16.0.0.rc3-h8456b07_1         conda-forge/label/llvm_rc
    libxml2:         2.10.3-hb9e07b5_0             conda-forge              
    libzlib:         1.2.13-hfd90126_4             conda-forge              
    llvm-tools:      16.0.0.rc3-h8456b07_1         conda-forge/label/llvm_rc
    llvmdev:         16.0.0.rc3-h8456b07_1         conda-forge/label/llvm_rc
    xz:              5.2.6-h775f41a_0              conda-forge              
    zlib:            1.2.13-hfd90126_4             conda-forge              
    zstd:            1.5.2-hbc0c0cd_6              conda-forge 
```
build env:
```
  environment location: /Users/runner/miniforge3/conda-bld/compiler-rt-packages_1677355103841/_build_env

The following NEW packages will be INSTALLED:

    bzip2:                  1.0.8-h0d85af4_4          conda-forge
    c-ares:                 1.18.1-h0d85af4_0         conda-forge
    ca-certificates:        2022.12.7-h033912b_0      conda-forge
    clang_bootstrap_osx-64: 14.0.6-h6ddedbb_4         conda-forge
    cmake:                  3.25.2-h4032537_0         conda-forge
    expat:                  2.5.0-hf0c8a7f_0          conda-forge
    krb5:                   1.20.1-h049b76e_0         conda-forge
    libcurl:                7.88.1-h6df9250_0         conda-forge
    libcxx:                 14.0.6-hccf4f1f_0         conda-forge
    libedit:                3.1.20191231-h0678c8f_2   conda-forge
    libev:                  4.33-haf1e3a3_1           conda-forge
    libffi:                 3.4.2-h0d85af4_5          conda-forge
    libnghttp2:             1.51.0-he2ab024_0         conda-forge
    libsqlite:              3.40.0-ha978bb4_0         conda-forge
    libssh2:                1.10.0-h47af595_3         conda-forge
    libuv:                  1.44.2-hac89ed1_0         conda-forge
    libzlib:                1.2.13-hfd90126_4         conda-forge
    ncurses:                6.3-h96cf925_1            conda-forge
    ninja:                  1.11.1-hb8565cd_0         conda-forge
    openssl:                3.0.8-hfd90126_0          conda-forge
    python:                 3.11.0-he7542f4_1_cpython conda-forge
    readline:               8.1.2-h3899abd_0          conda-forge
    rhash:                  1.4.3-hac89ed1_0          conda-forge
    tk:                     8.6.12-h5dbffcc_0         conda-forge
    tzdata:                 2022g-h191b570_0          conda-forge
    xz:                     5.2.6-h775f41a_0          conda-forge
    zlib:                   1.2.13-hfd90126_4         conda-forge
    zstd:                   1.5.2-hbc0c0cd_6          conda-forge
```

### Additional Context

Failing CI run [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=664408&view=results)

**Comment by 1player** [comment]
Welp, just hit this as well, when it worked on Linux and Windows. Is it possible to work around it by downgrading to an earlier version of conda-build?

**Comment by travishathaway** [comment]
Hi @h-vetinari,

Thanks for filing this bug. I dug a little deeper on this, and it turns out our usage of this particular library in conda-build is a bit fragile. In my opinion, I think it's probably to time refactor https://github.com/conda/conda-build/blob/main/conda_build/os_utils/liefldd.py and reconsider the way we use the `lief` package as a dependency in that module.

I've added the https://github.com/conda/conda-build/labels/good-first-issue label because this could be a reasonable task for someone new to the repository. Otherwise, we unfortunately cannot promise when this will be addressed.

**Comment by travishathaway** [comment]
@1player,

I don't think it's possible to work around this with an earlier version of conda-build. After viewing a git blame, I could see this code was added five years ago.

I think the work around fix for this is to somehow force install the version of `lief` that conda-build works with. I am currently not aware of which version this is though. This is a very undesirable route to go though, in my opinion.

**Comment by h-vetinari** [comment]
Looks like there's an upstream bug to track for this: https://github.com/lief-project/LIEF/issues/873

**Comment by isuruf** [comment]
The easiest way to work-around this would be to skip files ending with `.a` at https://github.com/conda/conda-build/blob/c5146a02c1b86033a7989718b1511969838db5dd/conda_build/post.py#L738
Collecting of dependencies of `.a` static libraries have never worked and is not expected to work as they do not have dependency info on them.

**Comment by h-vetinari** [comment]
Thanks a lot for the insight @isuruf! I opened a PR: https://github.com/conda/conda-build/pull/4808

**Comment by h-vetinari** [comment]
I think you misunderstand (or I do!)... This is not a question whether we package static libs (there are cases that are unavoidable, like compiler-builtins that you mention), but whether we run the lief-machinery on them that inspects the artefacts for their dependencies (and fails).

**Comment by 1player** [comment]
Any update? We're stuck because we need to build compiler-rt, and there are two PR that fix this exact issue.

**Comment by katietz** [comment]
yes, I agree. I ran into same issue with llvm/clang 16 building ... I patched lief/conda-build for it

**Comment by katietz** [comment]
I will share a PR with conda-build on the changes I made to it. In general it would be pretty good to have a switch in conda-build, which could be used to turn off the lief checks

**Comment by 1player** [comment]
There are two unmerged PRs that solve this bug already. 

They just need someone to review and merge one or the other.

**Comment by katietz** [comment]
I just read through them.  I think they both fix the issue here in particular, but there might be a way to resolve it more generic.  
Actually we should try to stop to run on something binary is  'NoneType' . But yes, looking and filtering out specific file-endings would be good.

Btw why this filtering of file-endings was removed anyway.  IIRC there was such a feature in the past, and now we attempt to run over any files in PREFIX with a lot of noise

**Comment by katietz** [comment]
see as suggestion to fix this the pull 4900, which does this in a more general way

**Comment by h-vetinari** [comment]
Doesn't hurt to link it: https://github.com/conda/conda-build/pull/4900

Fine by me, whatever gets this resolved, thanks! :)
