### ISSUE TITLE
Using `os.pathsep` worked in conda-build 25.3 & fails in 25.4

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#5704]
Given the following recipe

```yaml
# filename: use_os_pathsep_jinja/meta.yaml

package:
  name: use_os_pathsep_jinja
  version: 1

build:
  number: 0
  noarch: generic
  script:
    - echo "{{ os.pathsep }}"
```

With conda-build 25.3 this will print on UNIX `:` or Windows `;`

However conda-build 25.4 errors with

```python
CondaBuildUserError: Failed to render jinja template in /home/conda/use_os_pathsep_jinja/meta.yaml:
'type object' has no attribute 'pathsep'
```
